### ISSUE TITLE
 An error occurs when deploying this charts/sickhub/cronjobs

### ISSUE THREAD

**Issue by vldanch** [SickHub/charts#38]
Run command on gitlab runner:

`$ helm upgrade --install "${COMPONENT}" chartmuseum/cronjobs --version "${API_BACKEND_CHART_VERSION}" --namespace "${CI_K8S_NAMESPACE}" --values ./deploy/${VALUES}.yaml --wait --timeout "${HELM_TIMEOUT}"`

This error occurs on the gitlab runner:
```
Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: common
```
How can this error be fixed?

**Comment by vldanch** [comment]
@DrPsychick
Do you propose to add this common that was sent above to the chartmuseum?
And how then will the call to chartmuseum/cronjobs go, which contains the necessary values.yaml?

**Comment by DrPsychick** [comment]
I'll close this as there is no change required to the repo. Please reopen or create a new ticket if you think otherwise.
