### ISSUE TITLE
Charts cronjob 0.1.7

### ISSUE THREAD

**Issue by NaldoRay** [SickHub/charts#57]
First, thanks for your initiative and work on this project. 
I'm currently exploring K8s cronjob and found this project to be really useful.

I see cronjobs is already at 0.1.7 on main branch, but can't find the 0.1.7 release.
I need the new timezone config for the cronjob.

Any plan to release the new version? 
I don't know much about the CI/CD pipeline. Anything I can help?

**Comment by DrPsychick** [comment]
hmm, good point. I will make sure to fix this. Once changes have been merged it should build and publish the release.
