### ISSUE TITLE
CronJob metadata labels

### ISSUE THREAD

**Issue by torchello** [SickHub/charts#76]
Do I understand correctly that there is no way to add custom metadata labels to `CronJob`?

**Comment by DrPsychick** [comment]
You are right! That should not stay that way. Do you want to do an PR to add that feature?

**Comment by torchello** [comment]
Sure – https://github.com/SickHub/charts/pull/77. Not sure how to test though. Please check.

**Comment by torchello** [comment]
Seems like podAnnotations were never working as is: https://github.com/SickHub/charts/pull/78/files. Please have a look.
